repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv tool run ruff check --fix
        language: unsupported
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: uv tool run ruff format
        language: unsupported
        types: [python]

      - id: pyright
        name: pyright
        entry: uv tool run pyright src tests
        language: unsupported
        types: [python]
        pass_filenames: false
