[project]
name = "judge0"
version = "0.1.0.dev0"
description = "The official Python SDK for Judge0."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Judge0", email = "contact@judge0.com" }]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Intended Audience :: Developers",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Operating System :: OS Independent",
    "Operating System :: POSIX",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",

    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = ["httpx>=0.28.1,<1.0.0", "pydantic>=2.0.0,<3.0.0"]

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"

[project.urls]
Homepage = "https://github.com/judge0/judge0-python"
Repository = "https://github.com/judge0/judge0-python.git"
Issues = "https://github.com/judge0/judge0-python/issues"

[dependency-groups]
test = ["pytest==9.0.3", "python-dotenv==1.2.2", "pytest-cov==6.0.0"]
docs = [
    "sphinx==8.1.3",
    "sphinxawesome-theme==5.3.2",
    "sphinx-autodoc-typehints==2.3.0",
    "sphinx-multiversion==0.2.4",
    "sphinx-autobuild>=2024.10.3",
]
dev = [{ include-group = "test" }, { include-group = "docs" }]


[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "standard"
venvPath = "."
venv = ".venv"
reportMissingParameterType = "error"
reportReturnType = "error"
reportUnknownParameterType = "error"

[tool.pytest.ini_options]
addopts = "-vv"

[tool.uv]
exclude-newer = "28 days"
